version: '3'
services:
  sambad:
    image: "ghcr.io/pccsuite/pccsamba"
    depends_on:
      - postgres
    cap_add:
      - SYS_ADMIN
    hostname: ${PCC_SAMBA_HOSTNAME}
    # network_mode: host
    environment:
      - PCC_SAMBAAPI_DB_ADDR=postgres
      - PCC_SAMBAAPI_DB_NAME=postgres
      - PCC_SAMBAAPI_DB_USER=postgres
      - PCC_SAMBAAPI_DB_PASSWORD
      - PCC_SAMBA_ROLE_GROUPS
      - PCC_SAMBAAPI_TOKEN_INTROSPECT_URL
      - PCC_SAMBAAPI_TOKEN_INTROSPECT_AUTH
      - PCC_SAMBAAPI_TOKEN_REALM
      - PCC_SAMBAAPI_TOKEN_CLIENT
      - PCC_SAMBAAPI_HOMES_FILEPATH
    volumes:
      - type: bind
        source: ${PCC_SAMBA_DATA}/sambad/etc
        target: /etc/samba
      - type: bind
        source: ${PCC_SAMBA_DATA}/sambad/lib
        target: /var/lib/samba
      - type: bind
        source: ${PCC_SAMBA_DATA}/sambad/data
        target: /data
    ports:
      - 53:53
      - 53:53/udp
      - 88:88
      - 88:88/udp
      - 135:135
      - 137-138:137-138/udp
      - 139:139
      - 389:389
      - 389:389/udp
      - 445:445
      - 464:464
      - 464:464/udp
      - 636:636
      - 3268-3269:3268-3269
      - 8081:8081
    restart: unless-stopped
    pull_policy: always
  postgres:
    image: "postgres:latest"
    volumes:
      - type: bind
        source: ${PCC_SAMBA_DATA}/postgres
        target: /var/lib/postgresql/data
    environment:
      - "POSTGRES_PASSWORD=${PCC_SAMBAAPI_DB_PASSWORD}"
    restart: unless-stopped
    pull_policy: always