FROM alpine

### samba
RUN apk --no-cache --no-progress upgrade && \
    apk --no-cache --no-progress add bash samba shadow tini tzdata samba-dc krb5 ca-certificates samba-winbind-clients

EXPOSE 137/udp 138/udp 139 445

VOLUME ["/etc", "/var/cache/samba", "/var/lib/samba", "/var/log/samba", "/run/samba"]

## health check
HEALTHCHECK --interval=60s --timeout=15s \
            CMD smbclient -L \\localhost -U % -m SMB3

ENTRYPOINT [ "ionice", "-c", "3", "smbd", "-F", "--no-process-group" ]